PATH=$PATH:$HOME/.local/bin:$HOME/.local/share/appimages:/var/lib/flatpak/exports/bin:$HOME/.local/state/nix/profile/bin:$HOME/.local/share/mix/escripts:$HOME/.local/share/go/bin:$HOME/.local/share/gem/bin:$HOME/.local/share/cargo/bin

XDG_CACHE_HOME=$HOME/.cache
XDG_CONFIG_HOME=$HOME/.config
XDG_DATA_HOME=$HOME/.local/share

XDG_DESKTOP_DIR=$HOME/desktop
XDG_DOCUMENTS_DIR=$HOME/documents
XDG_DOWNLOAD_DIR=$HOME/downloads
XDG_MUSIC_DIR=$HOME/media/music
XDG_PICTURES_DIR=$HOME/media/pictures
XDG_PUBLICSHARE_DIR=$HOME/public
XDG_STATE_HOME=$HOME/.local/state
XDG_TEMPLATES_DIR=$HOME/templates
XDG_VIDEOS_DIR=$HOME/media/videos

_JAVA_AWT_WM_NONREPARENTING=1
_JAVA_OPTIONS=-Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
CALIBRE_USE_DARK_PALETTE=1
ELECTRON_OZONE_PLATFORM_HINT=wayland
GNUPGHOME=$XDG_DATA_HOME/gnupg
GTK2_RC_FILES=$XDG_CONFIG_HOME/gtk-2.0/gtkrc
GTK_BACKEND=wayland,x11,*
JAVA_FONTS=/usr/share/fonts/TTF
MOZ_ENABLE_WAYLAND=1
PASSWORD_STORE_DIR=$XDG_DATA_HOME/password-store
QT_AUTO_SCREEN_SCALE_FACTOR=1
QT_QPA_PLATFORM=wayland;xcb
QT_QPA_PLATFORMTHEME=qt6ct
QT_WAYLAND_DISABLE_WINDOWDECORATION=1
SDL_VIDEODRIVER=wayland,x11
WAYLAND_DISPLAY=wayland-1
WLR_NO_HARDWARE_CURSORS=1
XCURSOR_THEME=Quintom_Ink
YDOTOOL_SOCKET=/tmp/.ydotool_socket

BROWSER=brave
IMAGE=loupe
READER=papers
VIDEO=showtime

