abbr --add !! --position anywhere --function last_history_item
abbr --add edit_files --position command --regex ".+\.(conf|config|csv|dockerignore|env|envrc|gitattributes|gitignore|htm|html|ini|json|jsonc|lock|log|md|mod|nix|org|rss|sql|tex|toml|tsv|txt|typ|xhtml|xml|yaml|yml)" --function open_with_editor
abbr --add ca '$XDG_CACHE_HOME'
abbr --add cf '$XDG_CONFIG_HOME'
abbr --add cp 'cp -i'
abbr --add dc '$XDG_DOCUMENTS_DIR'
abbr --add dl '$XDG_DOWNLOAD_DIR'
abbr --add dot '$DOTFILES_DIR'
abbr --add e '$EDITOR'
abbr --add e. '$EDITOR .'
abbr --add eza 'eza '
abbr --add fd 'fd -H'
abbr --add ga 'git add'
abbr --add gaa 'git add .'
abbr --add gap 'git add -p'
abbr --add gb 'git branch'
abbr --add gc 'git commit -v'
abbr --add gca 'git commit --amend'
abbr --add gcb 'git checkout -b'
abbr --add gcl 'git clone'
abbr --add gcm --set-cursor 'git commit -m "%"'
abbr --add gco 'git switch'
abbr --add gd 'git diff'
abbr --add gf 'git fetch'
abbr --add glg 'git log --stat'
abbr --add gm 'git merge'
abbr --add gmv 'git mv'
abbr --add gob 'go build -v'
abbr --add gof 'gofmt -d -s -w .'
abbr --add gog 'go generate ./...'
abbr --add gpl 'git pull'
abbr --add gps 'git push'
abbr --add grb 'git rebase'
abbr --add grm 'git rm'
abbr --add grs 'git restore --staged .'
abbr --add gsh 'git secret hide'
abbr --add gsr 'git secret reveal -f'
abbr --add gst 'git status --short --branch'
abbr --add gsw 'git show'
abbr --add gw 'git worktree'
abbr --add gwc worktree-clone
abbr --add gwl 'git worktree list'
abbr --add gwp 'git worktree prune'
abbr --add gwr 'git worktree remove'
abbr --add hx helix
abbr --add la 'eza -T -L=3 --group-directories-first'
abbr --add lc '$HOME/.local/'
abbr --add lcb '$HOME/.local/bin/'
abbr --add lcs '$XDG_DATA_HOME'
abbr --add ls 'eza -1ar -s=Name --group-directories-first --git --icons=auto'
abbr --add mkdir 'mkdir -pv'
abbr --add mv 'mv -i'
abbr --add pro '$PROJECTS_DIR'
abbr --add src '$SOURCES_DIR'
abbr --add v nvim
abbr --add v. 'nvim .'
abbr --add wezterm 'flatpak run org.wezfurlong.wezterm'
abbr --add wget 'wget --hsts-file="$XDG_CACHE_HOME"/wget-hsts'
abbr --add work '$WORK_DIR'
