[tools]
ruby = "latest"
"gem:ruby-lsp" = "latest"
"gem:rubocop" = "latest"
"gem:erb-formatter" = "latest"
erlang = "latest"
elixir = "latest"
janet = "latest"
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"aqua:golangci/golangci-lint" = "latest"
"go:mvdan.cc/gofumpt" = "latest"

[settings]
idiomatic_version_file_enable_tools = []
experimental = true
