export PATH="$PATH":"$HOME/.local/bin":"/var/lib/flatpak/exports/bin":"$HOME/.local/state/nix/profile/bin":"$HOME/.local/share/mix/escripts":"$HOME/.local/share/go/bin"
# :"$HOME/.local/bin/scripts":"$XDG_DATA_HOME/go/bin":"$XDG_DATA_HOME/cargo/bin":"$XDG_DATA_HOME/gem/bin"

export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_DESKTOP_DIR="$HOME/desktop"
export XDG_DOCUMENTS_DIR="$HOME/documents"
export XDG_DOWNLOAD_DIR="$HOME/downloads"
export XDG_MUSIC_DIR="$HOME/media/music"
export XDG_PICTURES_DIR="$HOME/media/pictures"
export XDG_PUBLICSHARE_DIR="$HOME/public"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_TEMPLATES_DIR="$HOME/templates"
export XDG_VIDEOS_DIR="$HOME/media/videos"

export DOTFILES_DIR="$HOME/.dotfiles"
export WORK_DIR="$HOME/work"
export PROJECTS_DIR="$HOME/projects"
export SOURCES_DIR="$HOME/sources"

export ADB_KEYS_PATH="$ANDROID_PREFS_ROOT"
export ADB_VENDOR_KEY="$ANDROID_PREFS_ROOT"
export ANDROID_AVD_HOME="$XDG_DATA_HOME/android/"
export ANDROID_EMULATOR_HOME="$XDG_DATA_HOME/android/emulator"
export ANDROID_PREFS_ROOT="$XDG_CONFIG_HOME/android"
export ANDROID_SDK_HOME="$XDG_DATA_HOME/android/"
export CALIBRE_USE_DARK_PALETTE=1
export CARGO_HOME="$XDG_DATA_HOME/cargo"
# export CHROME_EXECUTABLE="/usr/bin/brave"
export FZF_DEFAULT_OPTS="-i"
export GEM_HOME="$XDG_DATA_HOME/gem"
export GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export GOPATH="$XDG_DATA_HOME/go"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
# export HEX_HOME="$XDG_DATA_HOME/hex"
export HISTFILE="$XDG_CACHE_HOME/history"
export JAVA_FONTS="/usr/share/fonts/TTF"
export LESSHISTFILE="-"
# export MIX_HOME="$XDG_DATA_HOME/mix"
export MIX_XDG="true"
export NODE_REPL_HISTORY="$XDG_CACHE_HOME/history/node_repl_history"
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export PYLINTHOME="$XDG_CACHE_HOME/pylint"
export PYTHONPYCACHEPREFIX="$XDG_CACHE_HOME/python"
export PYTHONUSERBASE="$XDG_DATA_HOME/python"
export PYTHON_HISTORY="$XDG_STATE_HOME/python/history"
export QT_QPA_PLATFORMTHEME="qt5ct"
export RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME/ripgrep/config"
export TMUX_TMPDIR="${XDG_RUNTIME_DIR:-"/run/user/$(id -u)"}"
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export YDOTOOL_SOCKET=/tmp/.ydotool_socket
export _JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_OPTIONS="-Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel"

export BROWSER="app.zen_browser.zen"
export EDITOR="nvim"
export IMAGE="imv"
export READER="zathura"
export TERM="foot"
export VIDEO="mpv"
export VISUAL="zed"
export MANPAGER="nvim +Man!"
