add_newline = false
command_timeout = 1000

[battery]
discharging_symbol = "󰂃"

[[battery.display]]
style = "bold red"
threshold = 10

[[battery.display]]
style = "bold yellow"
threshold = 30

[character]
error_symbol = "[](bold red)"
success_symbol = "[](bold green)"
vicmd_symbol = "[](bold yellow)"

[cmd_duration]
disabled = false

[directory]
fish_style_pwd_dir_length = 1
read_only = " "
read_only_style = "yellow"
style = "blue"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[erlang]
symbol = " "

[git_branch]
always_show_remote = true
symbol = " "

[git_commit]
tag_symbol = " "

[git_status]
ahead = "${count}"
behind = "${count}"
conflicted = "󰇼"
deleted = "󰆴"
diverged = "${ahead_count}⇣${behind_count}"
modified = ""
renamed = ""
staged = "[($count)](green)"
stashed = ""
style = "bold yellow"
untracked = ""

[golang]
symbol = "󰟓 "

[line_break]
disabled = false

[lua]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
format = "via [$symbol]($style)"
symbol = "󰎙 "

[package]
disabled = true
symbol = " "

[php]
symbol = "󰌟 "

[python]
format = "via [${symbol}(\\($virtualenv\\))]($style)"
style = "green"
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "󰛥 "
