[[language]]
name = "bash"
indent = { tab-width = 4, unit = " " }
formatter = { command = 'shfmt', args = ["-i", "4"] }
auto-format = true

[[language]]
name = "fish"
formatter = { command = "fish_indent" }
auto-format = true

[[language]]
name = "nix"
formatter = { command = "nixfmt" }
auto-format = true

[[language]]
name = "ruby"
auto-format = true

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "python"
language-servers = ["ruff"]
formatter = { command = "ruff", args = ["format", "-"] }
auto-format = true

[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[[language]]
name = "javascript"
auto-format = true
language-servers = ["biome"]

[[language]]
name = "typescript"
auto-format = true
language-servers = ["biome"]

[language-server.expert]
command = "expert"
args = ["--stdio"]

[[language]]
name = "elixir"
language-servers = ["expert"]
auto-format = true

[[language]]
name = "heex"
language-servers = ["expert"]
auto-format = true

[[language]]
name = "janet"
formatter = { command = "janet-format" }
auto-format = true

[[language]]
name = "go"
auto-format = true

[language-server.gopls.config]
"formatting.gofumpt" = true

[language-server.tinymist]
command = "tinymist"
config = { exportPdf = "onType", outputPath = "$root/target/$dir/$name", preview.background.enabled = true, preview.background.args = [
  "--data-plane-host=127.0.0.1:23635",
  "--invert-colors=never",
  "--open",
] }

[[language]]
name = "typst"
language-servers = ["tinymist"]

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]
config = { harper-ls.userDictPath = "$HOME/.dotfiles/base/.config/harper-ls/dictionary.txt" }

[[language]]
name = "markdown"
formatter = { command = "deno", args = [
  "fmt",
  "-",
  "--ext",
  "md",
  "--prose-wrap",
  "never",
] }
auto-format = true
language-servers = ["marksman", "markdown-oxide", "harper-ls"]
rulers = []
